# Tensorflow Essentials

In [4]:
import tensorflow as tf 
import numpy as np

***Aggregating tensors***

In [2]:
d = tf.constant([-7,-10])
d

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10])>

In [3]:
# Getting the absolute values
tf.abs(d)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10])>

In [12]:
var = tf.constant(np.random.randint(0,100,size=50))
var

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([ 7, 86, 43, 16, 71, 16, 95, 57, 83,  6, 29, 99, 10, 20, 12, 46, 12,
       94, 87, 54, 36, 48,  1,  7, 23, 59, 40, 51,  1, 32, 83, 73, 46, 10,
       51, 14, 94, 64, 29, 63, 78, 74, 43, 66, 58, 50,  3, 83, 42, 33])>

In [10]:
tf.size(var), var.shape, var.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [13]:
# Finding the min
tf.reduce_min(var)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [14]:
# Finding the max
tf.reduce_max(var)

<tf.Tensor: shape=(), dtype=int32, numpy=99>

In [15]:
# Finding the mean
tf.reduce_mean(var)

<tf.Tensor: shape=(), dtype=int32, numpy=45>

In [16]:
# Find the sum
tf.reduce_sum(var)

<tf.Tensor: shape=(), dtype=int32, numpy=2298>

In [21]:
#pip install tensorflow-probability

In [22]:
import tensorflow_probability as tfp

In [23]:
# Finding Variance
tfp.stats.variance(var)

<tf.Tensor: shape=(), dtype=int32, numpy=851>

In [26]:
tf.math.reduce_variance(tf.cast(var, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=850.71844>

In [25]:
# Finding the std
tf.math.reduce_std(tf.cast(var,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=29.167078>

***Finding the positional max and min***

In [27]:
# Creating a new tensor
tf.random.set_seed(42)
tensor = tf.random.uniform(shape=[50])
tensor

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [28]:
# Find the positional max
tf.argmax(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [30]:
# Index on the largest value
tensor[tf.argmax(tensor)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [31]:
# Check for equality 
tensor[tf.argmax(tensor)] == tf.reduce_max(tensor)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [32]:
# Find the positional min
tf.argmin(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [33]:
# The Smallest Val in Index
tensor[tf.argmin(tensor)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

***Squeezing a tensor (removing all the single dims)***

In [34]:
# Creating a tensor 
tf.random.set_seed(42)
var2 = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
var2

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [36]:
var2_squeezed = tf.squeeze(var2)
var2_squeezed, var2.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([1, 1, 1, 1, 50]))

***One-Hot Encoding tensors***

In [37]:
lst = [0,1,2,3]
tf.one_hot(lst, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [39]:
# Specify custom values for one hot encoding 
tf.one_hot(lst, depth=4, on_value="I love deep learning", off_value="I also like football")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'I love deep learning', b'I also like football',
        b'I also like football', b'I also like football'],
       [b'I also like football', b'I love deep learning',
        b'I also like football', b'I also like football'],
       [b'I also like football', b'I also like football',
        b'I love deep learning', b'I also like football'],
       [b'I also like football', b'I also like football',
        b'I also like football', b'I love deep learning']], dtype=object)>

***Maths operations***

In [41]:
mat = tf.range(1,10)
mat

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [42]:
tf.square(mat) # Sq

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [43]:
tf.sqrt(tf.cast(mat,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [44]:
tf.math.log(tf.cast(mat,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>