# Fundamentals of Tensorflow

In [1]:
import tensorflow as tf

**Sparse Tensor** <br>
A sparse tensor is a tensor in which most of the elements are zero (or some other specified "default" value). Storing such tensors in a dense format, where every value (including zeros) has a dedicated memory location, can be inefficient both in terms of memory and computational resources. 

In [2]:
tensor_s = tf.sparse.SparseTensor([[1,1],[3,4]],values= [11,56], dense_shape=[5,6])

In [3]:
tensor_s

SparseTensor(indices=tf.Tensor(
[[1 1]
 [3 4]], shape=(2, 2), dtype=int64), values=tf.Tensor([11 56], shape=(2,), dtype=int32), dense_shape=tf.Tensor([5 6], shape=(2,), dtype=int64))

**The Value [1,1], [3,4] refers to the index position of the tensor and the values consists of values i.e [11,56] in the dense tensor of shape 5x6**

In [4]:
tf.sparse.to_dense(tensor_s)

<tf.Tensor: shape=(5, 6), dtype=int32, numpy=
array([[ 0,  0,  0,  0,  0,  0],
       [ 0, 11,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 56,  0],
       [ 0,  0,  0,  0,  0,  0]])>

**Working With Tensor String**

In [7]:
st = "Hello, i am, a string"
lst = st.split(",")
tensor_str = tf.constant(lst)
print(tensor_str)

tf.Tensor([b'Hello' b' i am' b' a string'], shape=(3,), dtype=string)


In [9]:
# Joining the list to string 
tf.strings.join(tensor_str, separator='')

<tf.Tensor: shape=(), dtype=string, numpy=b'Hello i am a string'>

**Tensor Variables**

In [11]:
x =tf.constant([1,2])

In [12]:
x_var = tf.Variable(x, name='var1')
print(x_var)

<tf.Variable 'var1:0' shape=(2,) dtype=int32, numpy=array([1, 2])>


In [15]:
x_var.assign([3,4])
print(x_var)

<tf.Variable 'var1:0' shape=(2,) dtype=int32, numpy=array([3, 4])>


In [16]:
x_var.assign_sub([3,4])

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([0, 0])>