# Fundamentals of Tensorflow

In [1]:
import tensorflow as tf

**Inverse of Matrix and SVD (Single Value Decompose)**

In [5]:
tensor = tf.constant([[1,-2,0],
                     [3,5,100],
                     [2,3,8]],dtype=tf.float32)
tf.linalg.inv(tensor)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.4248366 , -0.02614375,  0.32679734],
       [-0.2875817 , -0.01307189,  0.1633987 ],
       [ 0.00163399,  0.01143791, -0.01797386]], dtype=float32)>

**SVD**, or Singular Value Decomposition, is a matrix factorization technique that decomposes a matrix into three other matrices

In [6]:
s,u,v = tf.linalg.svd(tensor)
print(s)
print(u)
print(v)

tf.Tensor([100.50496     3.3971667   1.792451 ], shape=(3,), dtype=float32)
tf.Tensor(
[[-7.2337181e-04 -4.6255928e-01  8.8658822e-01]
 [ 9.9666262e-01 -7.2704256e-02 -3.7118815e-02]
 [ 8.1628367e-02  8.8360238e-01  4.6106824e-01]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[ 0.03136679  0.319835    0.94695425]
 [ 0.05203373  0.9456129  -0.32110563]
 [ 0.9981526  -0.05934559 -0.01301867]], shape=(3, 3), dtype=float32)


**Ragged Tensor**
Ragged tensors in TensorFlow are used to handle and represent data that doesn't fit neatly into a rectangular shape. In other words, they are used to represent non-uniform or "ragged" multi-dimensional data.

In [7]:
tensor_1 = [[1,2,0],
           [3,],
           [3,5,6,5,6],
           [2,3,8]]
tensor_ragged = tf.ragged.constant(tensor_1)
print(tensor_ragged)

<tf.RaggedTensor [[1, 2, 0], [3], [3, 5, 6, 5, 6], [2, 3, 8]]>
