# Fundamentals of Tensorflow

In [1]:
import tensorflow as tf

In [2]:
id_matrix = tf.eye(3,3,dtype=tf.float16)
id_matrix

<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float16)>

**Fill Values Attribute to insert numbers directly in shape instead of multiplying**

In [3]:
fill_tensor = tf.fill([1,3,4],5)
fill_tensor

<tf.Tensor: shape=(1, 3, 4), dtype=int32, numpy=
array([[[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]]])>

In [4]:
ones_tensor = tf.ones([2,2,3],dtype=tf.float16)
ones_tensor

<tf.Tensor: shape=(2, 2, 3), dtype=float16, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]], dtype=float16)>

In [5]:
print(tf.shape(ones_tensor))

tf.Tensor([2 2 3], shape=(3,), dtype=int32)


In [6]:
tensor = tf.constant([[1,2,3],[4,5,6],[7,8,9]])
tf.rank(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [7]:
tf.size(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=9>

**Random Normal and Uniform Distribution**

In [8]:
tf.random.set_seed(42)
normal = tf.random.normal(shape=[5,5])
normal

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 0.3274685 , -0.8426258 ,  0.3194337 , -1.4075519 , -2.3880599 ],
       [-1.0392479 , -0.5573232 ,  0.539707  ,  1.6994323 ,  0.28893656],
       [-1.5066116 , -0.26454744, -0.59722406, -1.9171132 , -0.62044144],
       [ 0.8504023 , -0.40604794, -3.0258412 ,  0.9058464 ,  0.29855987],
       [-0.22561555, -0.7616443 , -1.891714  , -0.9384712 ,  0.77852213]],
      dtype=float32)>

In [9]:
uniform = tf.random.uniform(shape=[5,5],maxval=5,seed=42)
uniform

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[2.081514  , 1.3429081 , 2.3984158 , 1.8228567 , 4.773557  ],
       [4.709323  , 3.0741696 , 1.7921072 , 2.968012  , 1.0775548 ],
       [0.38725853, 2.8960657 , 1.4590198 , 1.3359016 , 1.8506229 ],
       [3.5805166 , 2.2938883 , 0.5882281 , 1.0536855 , 2.7209866 ],
       [4.9490347 , 1.9197929 , 0.2341783 , 4.359231  , 1.2940854 ]],
      dtype=float32)>

**Converts abs val into positive**

In [11]:
matrix_1d = tf.constant([-2.25,3.25])
tf.abs(matrix_1d)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2.25, 3.25], dtype=float32)>

In [12]:
x_abs_complex = tf.constant([-2.25+4.75j])
tf.abs(x_abs_complex)

<tf.Tensor: shape=(1,), dtype=float64, numpy=array([5.25594901])>

In [19]:
y = tf.constant([[-4.0], [16.0]])
tf.sqrt(y)

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[nan],
       [ 4.]], dtype=float32)>

In [27]:
x = tf.constant([1,2,3,4,5,6,7,8],dtype=tf.int32)
y = tf.constant([2,4,6,8,10,12,0,16],dtype=tf.int32)
print(tf.divide(x,y))
print(tf.math.divide_no_nan(tf.cast(x,dtype=tf.float32),tf.cast(y,dtype=tf.float32)))
print(tf.multiply(x,y))
print(tf.add(x,y))
print(tf.subtract(x,y))


tf.Tensor([0.5 0.5 0.5 0.5 0.5 0.5 inf 0.5], shape=(8,), dtype=float64)
tf.Tensor([0.5 0.5 0.5 0.5 0.5 0.5 0.  0.5], shape=(8,), dtype=float32)
tf.Tensor([  2   8  18  32  50  72   0 128], shape=(8,), dtype=int32)
tf.Tensor([ 3  6  9 12 15 18  7 24], shape=(8,), dtype=int32)
tf.Tensor([-1 -2 -3 -4 -5 -6  7 -8], shape=(8,), dtype=int32)


In [33]:
x_1 = tf.constant([5,3,6,6,4,6],dtype=tf.float32)
x_2 = tf.constant([[7], [5], [3]],dtype=tf.float32)
print(tf.math.multiply(x_1,x_2))
print(tf.math.minimum(x_1,x_2))
print(tf.math.maximum(x_1,x_2))
print(tf.pow(x_1,x_2))
print(tf.math.argmax(x_1))

tf.Tensor(
[[35. 21. 42. 42. 28. 42.]
 [25. 15. 30. 30. 20. 30.]
 [15.  9. 18. 18. 12. 18.]], shape=(3, 6), dtype=float32)
tf.Tensor(
[[5. 3. 6. 6. 4. 6.]
 [5. 3. 5. 5. 4. 5.]
 [3. 3. 3. 3. 3. 3.]], shape=(3, 6), dtype=float32)
tf.Tensor(
[[7. 7. 7. 7. 7. 7.]
 [5. 5. 6. 6. 5. 6.]
 [5. 3. 6. 6. 4. 6.]], shape=(3, 6), dtype=float32)
tf.Tensor(
[[7.81250e+04 2.18700e+03 2.79936e+05 2.79936e+05 1.63840e+04 2.79936e+05]
 [3.12500e+03 2.43000e+02 7.77600e+03 7.77600e+03 1.02400e+03 7.77600e+03]
 [1.25000e+02 2.70000e+01 2.16000e+02 2.16000e+02 6.40000e+01 2.16000e+02]], shape=(3, 6), dtype=float32)
tf.Tensor(2, shape=(), dtype=int64)


In [40]:
tensor_2d = tf.constant([[1,2,3],
                        [4,6,9],
                        [5,7,10]])
print(tf.math.reduce_sum(tensor_2d))
print(tf.math.reduce_min(tensor_2d))
print(tf.math.reduce_mean(tensor_2d))
print(tf.math.reduce_std(tf.cast(tensor_2d,dtype=tf.float16)))

tf.Tensor(47, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(2.898, shape=(), dtype=float16)


In [42]:
tf.math.top_k(tensor_2d,k=1)

TopKV2(values=<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[ 3],
       [ 9],
       [10]])>, indices=<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[2],
       [2],
       [2]])>)